version: '3'
networks:
  elastic:
    driver: bridge
services:
  redis:
    image: redis:7.2.2-alpine
    container_name: redis-test
    command: redis-server --port 6380
    ports:
      - 6380:6380
  mysql:
    image: mysql:5.7.43
    container_name: mysql-test
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: es-test
    networks:
      - elastic
    ports:
      - 9200:9200
    mem_limit: 1g